dist: bionic
language: minimal

#services:
#  - docker

before_install:
 - ./ci/ci.sh before_install

script:
  - sudo ./ci/ci.sh script
  # - sudo ./cmds/chroot-installer.sh
  # - sudo ./cmds/chroot-package.sh basic
  # - sudo ./cmds/chroot-live.sh
  # - sudo ./cmds/mksquashfs.sh
  # - sudo ./cmds/iso.sh

# deploy:
#   - provider: releases
#     overwrite: true
#     draft: false
#     prerelease: true
#     file: build/pack/*
#     edge: true
#     on:
#       tags: true
#       condition: $TRAVIS_TAG == edge
#
#   - provider: releases
#     overwrite: false
#     draft: false
#     prerelease: false
#     file: build/pack/*
#     edge: true
#     on:
#       tags: true
#       condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
#
#   - provider: script
#     edge: true
#     script: ./ci/ci.sh deploy_docker latest
#     on:
#       tags: true
#       condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
#
#   - provider: script
#     script: ./ci/ci.sh deploy_docker
#     edge: true
#     on:
#       tags: true
#       condition: $TRAVIS_TAG == edge
