dist: bionic
language: minimal

env:
  - DEBIAN_FRONTEND="noninteractive"

#services:
#  - docker

before_install:
 - echo 'Dpkg::Progress-Fancy "0";' | sudo tee /etc/apt/apt.conf.d/99progressbar
 - sudo chmod 644 99progressbar
 - sudo ./cmds/installer-prepare.sh

script:
  - ./cmds/x.sh build

# deploy:
#   - provider: releases
#     overwrite: true
#     draft: false
#     prerelease: true
#     file: build/pack/*
#     edge: true
#     on:
#       tags: true
#       condition: $TRAVIS_TAG == edge
#
#   - provider: releases
#     overwrite: false
#     draft: false
#     prerelease: false
#     file: build/pack/*
#     edge: true
#     on:
#       tags: true
#       condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
#
#   - provider: script
#     edge: true
#     script: ./ci/ci.sh deploy_docker latest
#     on:
#       tags: true
#       condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
#
#   - provider: script
#     script: ./ci/ci.sh deploy_docker
#     edge: true
#     on:
#       tags: true
#       condition: $TRAVIS_TAG == edge
