version: 2.1
jobs:
 docker:
   machine: true
   steps:
     - checkout
     - run: ./docker.sh build
 iso:
   machine:
    image: ubuntu-2004:202101-01
   steps:
     - checkout
     - run: ./build.sh clean
     - run: ./build.sh prepare
     - run: ./build.sh config_params | ./build.sh config
     - run: ./build.sh build_live_standard
     - run: ./build.sh build_checksum

workflows:
    version: 2
    build:
        jobs:
            - docker
            - iso