version: 2.1
jobs:
 docker:
   machine: true
   steps:
     - checkout
     - run: echo ./docker.sh build
 iso:
   machine: true
   steps:
     - checkout
     - run: ./build.sh clean
     - run: cmd_config_params | cmds/config.sh all
     - run: ./build.sh build_live_standard
     - run: ./build.sh build_checksum

workflows:
    version: 2
    build:
        jobs:
            - docker
            - iso